[package]
org = "mohamed"
name = "udp"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../udp-test-utils-0.8.0-SNAPSHOT.jar"
scope = "testOnly"
  